<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>gfoidl.Trx2Junit.Core</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Strings.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Strings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Strings.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Strings.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
