<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <PackAsTool>true</PackAsTool>
        <RollForward>Major</RollForward>
        <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\trx2junit.Core\trx2junit.Core.csproj" />
    </ItemGroup>

</Project>
